import { createWallet, inAppWallet, type WalletId } from 'thirdweb/wallets';

const AUTH_OPTIONS: ('google' | 'farcaster' | 'coinbase' | 'telegram')[] = [
	'google',
	'farcaster',
	'coinbase',
	'telegram',
];

const WALLET_IDS = [
	'io.metamask',
	'me.rainbow',
	'io.rabby',
	'global.safe',
	'org.uniswap',
	'com.trustwallet.app',
	'com.brave.wallet',
	'com.bitget.web3',
	'app.phantom',
	'com.exodus',
	'com.okex.wallet',
	'com.coinbase.wallet',
	'io.zerion.wallet',
	'io.1inch.wallet',
	'com.unstoppabledomains',
	'io.magiceden.wallet',
	'xyz.abs',
	'com.safepal',
	'ag.jup',
	'app.nicegram',
	'technology.jambo',
	'com.opera',
	'me.haha',
	'app.nightly',
	'app.subwallet',
	'app.backpack',
	'com.bybit',
	'pro.tokenpocket',
	'com.crypto.wallet',
	'com.fireblocks',
	'com.bitcoin',
	'com.ledger',
	'trade.flooz.wallet',
	'xyz.frontier.wallet',
	'xyz.argent',
	'io.loopring.wallet',
	'com.mewwallet',
	'org.mathwallet',
	'com.alphawallet',
	'com.roninchain.wallet',
	'com.coin98',
	'io.enjin',
	'io.oxalus',
	'io.leapwallet',
	'xyz.sequence',
	'it.airgap',
	'com.holdstation',
	'io.wallet3',
	'org.thorwallet',
	'app.krystal',
	'network.haqq',
	'com.foxwallet',
	'io.ozonewallet',
	'world.dosi.vault',
	'dev.auroracloud',
	'app.gamic',
	'io.hyperpay',
	'com.cakewallet',
	'io.ethos',
	'com.wemix',
	'com.azcoiner',
	'network.blackfort',
	'com.unitywallet',
	'com.hashpack.wallet',
	'xyz.echooo',
	'app.wombat',
	'com.safemoon',
	'com.bitpay',
	'com.webauth',
	'io.compasswallet',
	'social.gm2',
	'com.veworld',
	'app.core.extension',
	'me.komet.app',
	'io.uptn.dapp-web',
] as const;

export const bedlamWallets = [
	inAppWallet({
		auth: {
			options: AUTH_OPTIONS,
		},
	}),
	...WALLET_IDS.map((id) => createWallet(id as WalletId)),
];
